databases:
  - name: bytebusters
    databaseName: bytebusters_db
    user: bytebusters

services:
  - type: web
    name: bytebusters
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bytebusters
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false